### ISSUE TITLE
Original image downloading option.

### ISSUE THREAD

**Issue by DmytroJDS** [neoshell/EHentaiChromeExtension#1]
In some galleries below image page you can see note like that: "Download original 2126 x 3000 2.53 MB source". Is it possible to make extension to download also "originals" not only previews images?
Сomparison:
original image - 00.jpg :: 1280 x 1806 :: 385.9 KB
preview image - 00.jpg 2126 x 3000 2.53 MB

**Comment by neoshell** [comment]
Added the option in v1.0.2
